controller_manager:
  ros__parameters:
    update_rate: 10
    
    right_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


right_hand_controller:
  ros__parameters:
    joints:
      # - RH_yaw
      - RH_pitch
      - RH_roll
      - RH_elbow_joint
      # - RH_Revolute32
      # - RH_Revolute33
      # - RH_Revolute41
      # - RH_Revolute42
      # - RH_Revolute44
      - RH_wrist_roll

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true


# left_hand_controller:
#   ros__parameters:
#     joints:
#       - LH_yaw
#       - LH_pitch
#       - LH_roll
#       - LH_elbow_joint
#       # - LH_Revolute32
#       # - LH_Revolute33
#       # - LH_Revolute41
#       # - LH_Revolute42
#       # - LH_Revolute44
#       - LH_wrist_roll

#     command_interfaces:
#       - position

#     state_interfaces:
#       - position

#     open_loop_control: true
#     allow_integration_in_goal_trajectories: true



