controller_manager:
  ros__parameters:
    update_rate: 10

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_controllers:
      type: joint_trajectory_controller/JointTrajectoryController

joint_controllers:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - Joint1
      # - Joint2
      # - Joint3
